pipeline {
  agent any

  stages {
    stage('build') {
      steps {
        echo "build"
      }
    }
    stage('testing') {
      steps {
        echo "tested"
      }
    }
    stage('deploy') {
      steps {
        echo "deployed"
      }
    }
  }
}
